version: "3.8"

services:
  backend:
    build: .
    container_name: fintrack-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: fintrack-backend
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-d3vfn3ili9vc73cppo40-a.oregon-postgres.render.com:5432/finanzas_db_no00
      SPRING_DATASOURCE_USERNAME: finanzas_db_no00_user
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: my_super_secret_jwt_key_1234567890123456
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP_CONVERTER_JSON: DEBUG
    networks:
      - finanzas-network

networks:
  finanzas-network:
    driver: bridge
